providers = ["...", "node", "go"]

[phases.setup]
nixPkgs = ["...", "go", "templ", "nodejs_22"]

[phases.builder]
cmds = [
  "npm install -g tailwindcss",
  "npm run build:tailwind",
  "go mod tidy",
  "templ generate",
  "go build -ldflags \"-X main.Environment=production\" -o ./bin/app ./cmd/main.go"
]

[start]
cmd = "./bin/app"